<!DOCTYPE html><html lang="zh-CN" ><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name="generator" content="Jekyll v4.2.2" /><meta property="og:title" content="Create a Solid of Rotation using MicroStation VBA" /><meta name="author" content="网格转载" /><meta property="og:locale" content="zh_CN" /><meta name="description" content="A minimal, responsive, and powerful Jekyll theme for presenting professional writing." /><meta property="og:description" content="A minimal, responsive, and powerful Jekyll theme for presenting professional writing." /><link rel="canonical" href="https://www.cehui.ren/posts/mstn-vba-Create-a-Solid-of-Rotation/" /><meta property="og:url" content="https://www.cehui.ren/posts/mstn-vba-Create-a-Solid-of-Rotation/" /><meta property="og:site_name" content="测量老覃’s blog" /><meta property="og:type" content="article" /><meta property="article:published_time" content="2009-02-02T09:36:00+08:00" /><meta name="twitter:card" content="summary" /><meta property="twitter:title" content="Create a Solid of Rotation using MicroStation VBA" /><meta name="twitter:site" content="@qd_xyz" /><meta name="twitter:creator" content="@网格转载" /> <script type="application/ld+json"> {"@context":"https://schema.org","@type":"BlogPosting","author":{"@type":"Person","name":"网格转载"},"dateModified":"2009-02-02T09:36:00+08:00","datePublished":"2009-02-02T09:36:00+08:00","description":"A minimal, responsive, and powerful Jekyll theme for presenting professional writing.","headline":"Create a Solid of Rotation using MicroStation VBA","mainEntityOfPage":{"@type":"WebPage","@id":"https://www.cehui.ren/posts/mstn-vba-Create-a-Solid-of-Rotation/"},"url":"https://www.cehui.ren/posts/mstn-vba-Create-a-Solid-of-Rotation/"}</script><title>Create a Solid of Rotation using MicroStation VBA | 测量老覃's blog</title><link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicons/favicon-16x16.png"><link rel="manifest" href="/assets/img/favicons/site.webmanifest"><link rel="shortcut icon" href="/assets/img/favicons/favicon.ico"><meta name="apple-mobile-web-app-title" content="测量老覃's blog"><meta name="application-name" content="测量老覃's blog"><meta name="msapplication-TileColor" content="#da532c"><meta name="msapplication-config" content="/assets/img/favicons/browserconfig.xml"><meta name="theme-color" content="#ffffff"><link rel="preconnect" href="https://fonts.googleapis.com" ><link rel="dns-prefetch" href="https://fonts.googleapis.com" ><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="dns-prefetch" href="https://fonts.gstatic.com" crossorigin><link rel="preconnect" href="https://fonts.googleapis.com" ><link rel="dns-prefetch" href="https://fonts.googleapis.com" ><link rel="preconnect" href="https://cdn.jsdelivr.net" ><link rel="dns-prefetch" href="https://cdn.jsdelivr.net" ><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato&family=Source+Sans+Pro:wght@400;600;700;900&display=swap"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.11.2/css/all.min.css"><link rel="stylesheet" href="/assets/css/style.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/magnific-popup@1/dist/magnific-popup.min.css"> <script src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"></script> <script type="text/javascript"> class ModeToggle { static get MODE_KEY() { return "mode"; } static get MODE_ATTR() { return "data-mode"; } static get DARK_MODE() { return "dark"; } static get LIGHT_MODE() { return "light"; } static get ID() { return "mode-toggle"; } constructor() { if (this.hasMode) { if (this.isDarkMode) { if (!this.isSysDarkPrefer) { this.setDark(); } } else { if (this.isSysDarkPrefer) { this.setLight(); } } } let self = this; /* always follow the system prefers */ this.sysDarkPrefers.addEventListener("change", () => { if (self.hasMode) { if (self.isDarkMode) { if (!self.isSysDarkPrefer) { self.setDark(); } } else { if (self.isSysDarkPrefer) { self.setLight(); } } self.clearMode(); } self.notify(); }); } /* constructor() */ get sysDarkPrefers() { return window.matchMedia("(prefers-color-scheme: dark)"); } get isSysDarkPrefer() { return this.sysDarkPrefers.matches; } get isDarkMode() { return this.mode === ModeToggle.DARK_MODE; } get isLightMode() { return this.mode === ModeToggle.LIGHT_MODE; } get hasMode() { return this.mode != null; } get mode() { return sessionStorage.getItem(ModeToggle.MODE_KEY); } /* get the current mode on screen */ get modeStatus() { if (this.isDarkMode || (!this.hasMode && this.isSysDarkPrefer)) { return ModeToggle.DARK_MODE; } else { return ModeToggle.LIGHT_MODE; } } setDark() { $('html').attr(ModeToggle.MODE_ATTR, ModeToggle.DARK_MODE); sessionStorage.setItem(ModeToggle.MODE_KEY, ModeToggle.DARK_MODE); } setLight() { $('html').attr(ModeToggle.MODE_ATTR, ModeToggle.LIGHT_MODE); sessionStorage.setItem(ModeToggle.MODE_KEY, ModeToggle.LIGHT_MODE); } clearMode() { $('html').removeAttr(ModeToggle.MODE_ATTR); sessionStorage.removeItem(ModeToggle.MODE_KEY); } /* Notify another plugins that the theme mode has changed */ notify() { window.postMessage({ direction: ModeToggle.ID, message: this.modeStatus }, "*"); } } /* ModeToggle */ const toggle = new ModeToggle(); function flipMode() { if (toggle.hasMode) { if (toggle.isSysDarkPrefer) { if (toggle.isLightMode) { toggle.clearMode(); } else { toggle.setLight(); } } else { if (toggle.isDarkMode) { toggle.clearMode(); } else { toggle.setDark(); } } } else { if (toggle.isSysDarkPrefer) { toggle.setLight(); } else { toggle.setDark(); } } toggle.notify(); } /* flipMode() */ </script><body data-spy="scroll" data-target="#toc" data-topbar-visible="true"><div id="sidebar" class="d-flex flex-column align-items-end"><div class="profile-wrapper text-center"><div id="avatar"> <a href="/" class="mx-auto"> <img src="/img/avatar.jpg" alt="avatar" onerror="this.style.display='none'"> </a></div><div class="site-title mt-3"> <a href="/">测量老覃's blog</a></div><div class="site-subtitle font-italic">www.cehui.ren</div></div><ul class="w-100"><li class="nav-item"> <a href="/" class="nav-link"> <i class="fa-fw fas fa-home ml-xl-3 mr-xl-3 unloaded"></i> <span>首页</span> </a><li class="nav-item"> <a href="/categories/" class="nav-link"> <i class="fa-fw fas fa-stream ml-xl-3 mr-xl-3 unloaded"></i> <span>分类</span> </a><li class="nav-item"> <a href="/tags/" class="nav-link"> <i class="fa-fw fas fa-tag ml-xl-3 mr-xl-3 unloaded"></i> <span>标签</span> </a><li class="nav-item"> <a href="/archives/" class="nav-link"> <i class="fa-fw fas fa-archive ml-xl-3 mr-xl-3 unloaded"></i> <span>归档</span> </a><li class="nav-item"> <a href="/about/" class="nav-link"> <i class="fa-fw fas fa-info-circle ml-xl-3 mr-xl-3 unloaded"></i> <span>关于</span> </a></ul><div class="sidebar-bottom mt-auto d-flex flex-wrap justify-content-center align-items-center"> <button class="mode-toggle btn" aria-label="Switch Mode"> <i class="fas fa-adjust"></i> </button> <span class="icon-border"></span> <a href="https://github.com/qin-dong" aria-label="stack-overflow" target="_blank" rel="noopener"> <i class="fab fa-github"></i> </a> <a href="https://twitter.com/qd_xyz" aria-label="twitter" target="_blank" rel="noopener"> <i class="fab fa-twitter"></i> </a> <a href=" javascript:location.href = 'mailto:' + ['qd.xyz','139.com'].join('@')" aria-label="email" > <i class="fas fa-envelope"></i> </a> <a href="/feed.xml" aria-label="rss" target="_blank" rel="noopener"> <i class="fas fa-rss"></i> </a></div></div><div id="topbar-wrapper"><div id="topbar" class="container d-flex align-items-center justify-content-between h-100 pl-3 pr-3 pl-md-4 pr-md-4"> <span id="breadcrumb"> <span> <a href="/"> 首页 </a> </span> <span>Create a Solid of Rotation using MicroStation VBA</span> </span> <i id="sidebar-trigger" class="fas fa-bars fa-fw"></i><div id="topbar-title"> 文章</div><i id="search-trigger" class="fas fa-search fa-fw"></i> <span id="search-wrapper" class="align-items-center"> <i class="fas fa-search fa-fw"></i> <input class="form-control" id="search-input" type="search" aria-label="search" autocomplete="off" placeholder="搜索..."> </span> <span id="search-cancel" >取消</span></div></div><div id="main-wrapper" class="d-flex justify-content-center"><div id="main" class="container pl-xl-4 pr-xl-4"><div class="row"><div id="core-wrapper" class="col-12 col-lg-11 col-xl-9 pr-xl-4 pb-5"><div class="post pl-1 pr-1 pl-md-2 pr-md-2"><h1 data-toc-skip>Create a Solid of Rotation using MicroStation VBA</h1><div class="post-meta text-muted"> <span> 发表于 <em class="" data-ts="1233538560" data-df="YYYY-MM-DD" data-toggle="tooltip" data-placement="bottom"> 2009-02-02 </em> </span><div class="d-flex justify-content-between"> <span> 作者 <em> <a href=""></a> </em> </span><div> <span class="readtime" data-toggle="tooltip" data-placement="bottom" title="678 字"> <em>3 分钟</em>阅读</span></div></div></div><div class="post-content"><ul id="markdown-toc"><li><a href="#smartsolids" id="markdown-toc-smartsolids">SmartSolids</a><li><a href="#solid-of-rotation" id="markdown-toc-solid-of-rotation">Solid of Rotation</a><ul><li><a href="#2d-profile" id="markdown-toc-2d-profile">2D Profile</a><li><a href="#rotation-parameters" id="markdown-toc-rotation-parameters">Rotation Parameters</a><li><a href="#rotate-profile" id="markdown-toc-rotate-profile">Rotate Profile</a><li><a href="#cap-surface" id="markdown-toc-cap-surface">Cap Surface</a></ul><li><a href="#problems" id="markdown-toc-problems">Problems</a><li><a href="#questions" id="markdown-toc-questions">Questions</a></ul><p>This page lists some solutions to common MicroStation VBA (MVBA) problems. Tips are published as examples and are not necessarily working code.</p><h2 id="smartsolids"><span class="mr-2">SmartSolids</span><a href="#smartsolids" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h2><p>Bentley Systems add the <strong>SmartSolid</strong> class to MicroStation VBA in a late version of MicroStation V8i. It continues to be available with MicroStation CONNECT. There are two related classes. The comments are taken from MicroStation VBA help …</p><ul><li><strong>SmartSolid</strong>: Holds generic methods useful in dealing with SmartSolid objects<li><strong>SmartSolidElement</strong>: A kind of Element that corresponds to a MicroStation SmartSolid/SmartSurface element</ul><p>In other words, the <strong>SmartSolid</strong> class is an implementation of mathematical concepts that help us create and manipulate 3D solid objects. The <strong>SmartSolidElement</strong> class provide tools to handle a 3D solid as a MicroStation DGN element.</p><h2 id="solid-of-rotation"><span class="mr-2">Solid of Rotation</span><a href="#solid-of-rotation" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h2><p>We can create a solid of rotation by first identifying or creating a 2D profile. Next, we rotate the profile about a given point, in a given orientation, by a specified angle. The VBA method is <strong>SmartSolid.RevolveProfile</strong>.</p><h3 id="2d-profile"><span class="mr-2">2D Profile</span><a href="#2d-profile" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h3><p>Look at the VBA documentation for <strong>SmartSolid.RevolveProfile</strong>: Revolves a wire or sheet body about the axis passing through the point and along the axis.</p><p>The profile element is a DGN element: profile body which is swept along the path, it should not be a closed curve.</p><p>A profile is a two-dimensional open shape. You can create such an element from a simple line-string or other primitive curve, or a complex string. Here’s an example …</p><div class="language-vb highlighter-rouge"><div class="code-header"> <span data-label-text="Visual Basic"><i class="fas fa-code small"></i></span> <button aria-label="copy" data-title-succeed="已复制！"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
</pre><td class="rouge-code"><pre><span class="k">Dim</span> <span class="nv">profileElements</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span> <span class="ow">As</span> <span class="n">ChainableElement</span>

<span class="k">Set</span> <span class="n">profileElements</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span> <span class="o">=</span> <span class="n">CreateLineElement2</span><span class="p">(</span><span class="k">Nothing</span><span class="p">,</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0591</span><span class="p">,</span> <span class="mf">0.0245</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0836</span><span class="p">,</span> <span class="mf">0.0806</span><span class="p">,</span> <span class="mi">0</span><span class="p">))</span>
<span class="k">Set</span> <span class="n">profileElements</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span> <span class="o">=</span> <span class="n">CreateLineElement2</span><span class="p">(</span><span class="k">Nothing</span><span class="p">,</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0836</span><span class="p">,</span> <span class="mf">0.0806</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0899</span><span class="p">,</span> <span class="mf">0.0792</span><span class="p">,</span> <span class="mi">0</span><span class="p">))</span>
<span class="k">Set</span> <span class="n">profileElements</span><span class="p">(</span><span class="mi">2</span><span class="p">)</span> <span class="o">=</span> <span class="n">CreateLineElement2</span><span class="p">(</span><span class="k">Nothing</span><span class="p">,</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0899</span><span class="p">,</span> <span class="mf">0.0792</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0899</span><span class="p">,</span> <span class="mf">0.0203</span><span class="p">,</span> <span class="mi">0</span><span class="p">))</span>
<span class="k">Set</span> <span class="n">profileElements</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span> <span class="o">=</span> <span class="n">CreateLineElement2</span><span class="p">(</span><span class="k">Nothing</span><span class="p">,</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0899</span><span class="p">,</span> <span class="mf">0.0203</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="n">Point3dFromXYZ</span><span class="p">(</span><span class="mf">0.0591</span><span class="p">,</span> <span class="mf">0.0245</span><span class="p">,</span> <span class="mi">0</span><span class="p">))</span>

<span class="k">Dim</span> <span class="nv">oProfile</span> <span class="ow">As</span> <span class="n">ComplexStringElement</span>
<span class="k">Set</span> <span class="n">oProfile</span> <span class="o">=</span> <span class="n">CreateComplexStringElement1</span><span class="p">(</span><span class="n">profileElements</span><span class="p">())</span>
</pre></table></code></div></div><h3 id="rotation-parameters"><span class="mr-2">Rotation Parameters</span><a href="#rotation-parameters" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h3><p>Next, decide how to rotate that profile. We need a point to rotate about, an axis of rotation, and a rotation angle (the angle, as is usual, is measured in Radians) …</p><div class="language-vb highlighter-rouge"><div class="code-header"> <span data-label-text="Visual Basic"><i class="fas fa-code small"></i></span> <button aria-label="copy" data-title-succeed="已复制！"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
</pre><td class="rouge-code"><pre><span class="k">Dim</span> <span class="nv">pointOfRotation</span> <span class="ow">As</span> <span class="n">Point3d</span>
<span class="n">pointOfRotation</span> <span class="o">=</span> <span class="n">Point3dZero</span>

<span class="k">Dim</span> <span class="nv">xAxis</span> <span class="ow">As</span> <span class="n">Vector3d</span>
<span class="c1">'  Rotate about the X-axis</span>
<span class="n">xAxis</span> <span class="o">=</span> <span class="n">Vector3dFromXYZ</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">Dim</span> <span class="nv">rotateAngle</span> <span class="ow">As</span> <span class="kt">Double</span>
<span class="c1">'  Rotate by Pi radians (180°)</span>
<span class="n">rotateAngle</span> <span class="o">=</span> <span class="n">Pi</span>
</pre></table></code></div></div><h3 id="rotate-profile"><span class="mr-2">Rotate Profile</span><a href="#rotate-profile" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h3><p>Now everything is ready. We’re going to create a <strong>SmartSolidElement</strong> that can be added to a DGN model. We create that <strong>SmartSolidElement</strong> using the <strong>RevolveProfile</strong> method of class <strong>SmartSolid</strong>. The actual rotation is quite simple …</p><div class="language-vb highlighter-rouge"><div class="code-header"> <span data-label-text="Visual Basic"><i class="fas fa-code small"></i></span> <button aria-label="copy" data-title-succeed="已复制！"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
</pre><td class="rouge-code"><pre><span class="k">Dim</span> <span class="nv">oBodySolid</span> <span class="ow">As</span> <span class="n">SmartSolidElement</span>
<span class="k">Set</span> <span class="n">oBodySolid</span> <span class="o">=</span> <span class="n">SmartSolid</span><span class="p">.</span><span class="n">RevolveProfile</span><span class="p">(</span><span class="n">oProfile</span><span class="p">,</span> <span class="n">pointOfRotation</span><span class="p">,</span> <span class="n">xAxis</span><span class="p">,</span> <span class="n">rotateAngle</span><span class="p">)</span>
</pre></table></code></div></div><h3 id="cap-surface"><span class="mr-2">Cap Surface</span><a href="#cap-surface" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h3><p>Finally, you may want to call <strong>SmartSolidElement.CapSurface</strong>. That ensures that you create a 3D solid rather than a 3D surface. Or, as VBA help puts it: Converts a sheet body to a solid by adding faces to fill up “hollow spaces”.</p><div class="language-vb highlighter-rouge"><div class="code-header"> <span data-label-text="Visual Basic"><i class="fas fa-code small"></i></span> <button aria-label="copy" data-title-succeed="已复制！"><i class="far fa-clipboard"></i></button></div><div class="highlight"><code><table class="rouge-table"><tbody><tr><td class="rouge-gutter gl"><pre class="lineno">1
2
</pre><td class="rouge-code"><pre><span class="n">oBodySolid</span><span class="p">.</span><span class="n">CapSurface</span>
<span class="n">ActiveModelReference</span><span class="p">.</span><span class="n">AddElement</span> <span class="n">oBodySolid</span>
</pre></table></code></div></div><p>Here’s a screenshot of the resulting solid …</p><p><img data-src="/img/2022/2022-09-20-09-52-22.png" alt="" data-proofer-ignore> <em>Rotated Profile</em></p><h2 id="problems"><span class="mr-2">Problems</span><a href="#problems" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h2><p>Some people have reported problems using <strong>SmartSolidElement.RevolveProfile</strong>. Here are some comments …</p><ul><li>The profile of rotation must be an open element. It should not be a closed shape<li>The angle of rotation is specified in radians, not degrees. Note that if you intend to rotate by, say, 180° and specify 180 for the rotation, that is about 10313°, which is quite a few rotations and probably not what you intended. VBA provides a conversion function <strong>Radians()</strong>, so you’ve no excuse for not using radians<li>The axis of rotation is define by a vector. If you want to rotate about the Z axis that vector is 0,0,1 (the example above rotates about the X axis)<li>The origin and range of the resulting solid must conform to MicroStation’s rules for solids, in particular the solid working area</ul><p>MicroStation VBA developer Paul Rowlands commented, after struggling with <strong>SmartSolidElement.RevolveProfile</strong>: Cause of the problem is global origins set at large values which a certain infrastructure client likes to use in their seed files</p><h2 id="questions"><span class="mr-2">Questions</span><a href="#questions" class="anchor text-muted"><i class="fas fa-hashtag"></i></a></h2><p>Post questions about MicroStation programming to the <a href="https://communities.bentley.com/products/programming/microstation_programming/f/microstation-programming---forum">MicroStation Programming Forum</a>.</p></div><div class="post-tail-wrapper text-muted"><div class="post-meta mb-3"> <i class="far fa-folder-open fa-fw mr-1"></i> <a href='/categories/%E7%BC%96%E7%A8%8B%E5%BC%80%E5%8F%91/'>编程开发</a>, <a href='/categories/vba-microstation/'>VBA-MicroStation</a></div><div class="post-tags"> <i class="fa fa-tags fa-fw mr-1"></i> <a href="/tags/%E5%89%96%E9%9D%A2/" class="post-tag no-text-decoration" >剖面</a> <a href="/tags/%E5%AE%9E%E4%BD%93/" class="post-tag no-text-decoration" >实体</a> <a href="/tags/%E4%BB%A3%E7%A0%81/" class="post-tag no-text-decoration" >代码</a></div><div class="post-tail-bottom d-flex justify-content-between align-items-center mt-3 pt-5 pb-2"><div class="license-wrapper"> 本文由作者按照 <a href="https://creativecommons.org/licenses/by/4.0/"> CC BY 4.0 </a> 进行授权</div><div class="share-wrapper"> <span class="share-label text-muted mr-1">分享</span> <span class="share-icons"> <a href="https://twitter.com/intent/tweet?text=Create+a+Solid+of+Rotation+using+MicroStation+VBA+-+%E6%B5%8B%E9%87%8F%E8%80%81%E8%A6%83%27s+blog&url=https%3A%2F%2Fwww.cehui.ren%2Fposts%2Fmstn-vba-Create-a-Solid-of-Rotation%2F" data-toggle="tooltip" data-placement="top" title="Twitter" target="_blank" rel="noopener" aria-label="Twitter"> <i class="fa-fw fab fa-twitter"></i> </a> <a href="https://www.facebook.com/sharer/sharer.php?title=Create+a+Solid+of+Rotation+using+MicroStation+VBA+-+%E6%B5%8B%E9%87%8F%E8%80%81%E8%A6%83%27s+blog&u=https%3A%2F%2Fwww.cehui.ren%2Fposts%2Fmstn-vba-Create-a-Solid-of-Rotation%2F" data-toggle="tooltip" data-placement="top" title="Facebook" target="_blank" rel="noopener" aria-label="Facebook"> <i class="fa-fw fab fa-facebook-square"></i> </a> <a href="https://t.me/share/url?url=https%3A%2F%2Fwww.cehui.ren%2Fposts%2Fmstn-vba-Create-a-Solid-of-Rotation%2F&text=Create+a+Solid+of+Rotation+using+MicroStation+VBA+-+%E6%B5%8B%E9%87%8F%E8%80%81%E8%A6%83%27s+blog" data-toggle="tooltip" data-placement="top" title="Telegram" target="_blank" rel="noopener" aria-label="Telegram"> <i class="fa-fw fab fa-telegram"></i> </a> <a href="http://service.weibo.com/share/share.php?title=Create+a+Solid+of+Rotation+using+MicroStation+VBA+-+%E6%B5%8B%E9%87%8F%E8%80%81%E8%A6%83%27s+blog&url=https%3A%2F%2Fwww.cehui.ren%2Fposts%2Fmstn-vba-Create-a-Solid-of-Rotation%2F" data-toggle="tooltip" data-placement="top" title="Weibo" target="_blank" rel="noopener" aria-label="Weibo"> <i class="fa-fw fab fa-weibo"></i> </a> <i id="copy-link" class="fa-fw fas fa-link small" data-toggle="tooltip" data-placement="top" title="分享链接" data-title-succeed="链接已复制！"> </i> </span></div></div></div></div></div><div id="panel-wrapper" class="col-xl-3 pl-2 text-muted"><div class="access"><div id="access-lastmod" class="post"><div class="panel-heading">最近更新</div><ul class="post-content pl-0 pb-1 ml-1 mt-2"><li><a href="/posts/autolisp-draw-3d-entity-code/">AutoLISP绘三维对象实体代码</a><li><a href="/posts/autolisp-layout-cass-points-draw-small-sphere/">AutoLISP源代码展CASS地形点生成三维小球体检查超欠挖</a><li><a href="/posts/mstn-accudraw-commands-hotkeys-list/">MicroStation精确绘图快捷键入命令的完整列表</a><li><a href="/posts/ord-plan-by-3D-element-smartline-create-alignment/">OpenRoads普通三维线段转化为Civil几何路线</a><li><a href="/posts/autocad-linework-commands/">AutoCAD编辑处理线构件LINEWORK相关命令</a></ul></div><div id="access-tags"><div class="panel-heading">热门标签</div><div class="d-flex flex-wrap mt-3 mb-1 mr-3"> <a class="post-tag" href="/tags/microstation/">MicroStation</a> <a class="post-tag" href="/tags/vba/">VBA</a> <a class="post-tag" href="/tags/%E4%BB%A3%E7%A0%81/">代码</a> <a class="post-tag" href="/tags/xm/">XM</a> <a class="post-tag" href="/tags/openroads/">OpenRoads</a> <a class="post-tag" href="/tags/key-in/">key-in</a> <a class="post-tag" href="/tags/%E6%96%B9%E9%87%8F/">方量</a> <a class="post-tag" href="/tags/civil3d/">Civil3D</a> <a class="post-tag" href="/tags/%E6%95%99%E7%A8%8B/">教程</a> <a class="post-tag" href="/tags/%E6%96%AD%E9%9D%A2/">断面</a></div></div></div><script src="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.js"></script><div id="toc-wrapper" class="pl-0 pr-4 mb-5"><div class="panel-heading pl-3 pt-2 mb-2">文章内容</div><nav id="toc" data-toggle="toc"></nav></div></div></div><div class="row"><div id="tail-wrapper" class="col-12 col-lg-11 col-xl-9 pl-3 pr-3 pr-xl-4"><div id="related-posts" class="mb-2 mb-sm-4"><h3 class="pt-2 mb-4 ml-1" data-toc-skip>相关文章</h3><div class="card-deck mb-4"><div class="card"> <a href="/posts/mstn-vba-create-line-code/"><div class="card-body"> <em class="small" data-ts="1580659200" data-df="YYYY-MM-DD" > 2020-02-03 </em><h3 class="pt-0 mt-1 mb-3" data-toc-skip>MicroStation VBA-创建直线代码(CreateLineTest)</h3><div class="text-muted small"><p> This function requires 2 points to create a line, which we then may place into the drawing. A VBA code example using this function may look like this: 1 2 3 4 5 6 7 8 9 Sub CreateLineTest() Dim o...</p></div></div></a></div><div class="card"> <a href="/posts/mstn-vba-Automatic-Subroutine-Loading/"><div class="card-body"> <em class="small" data-ts="1580832000" data-df="YYYY-MM-DD" > 2020-02-05 </em><h3 class="pt-0 mt-1 mb-3" data-toc-skip>MicroStation VBA-Automatic Subroutine Loading</h3><div class="text-muted small"><p> The naming of a subroutine generally does not matter. One exception, however, is the name OnProjectLoad. If a subroutine gets this name, it is automatically started as soon as it is loaded. This m...</p></div></div></a></div><div class="card"> <a href="/posts/mstn-vba-create-arc-modify-properties/"><div class="card-body"> <em class="small" data-ts="1580832000" data-df="YYYY-MM-DD" > 2020-02-05 </em><h3 class="pt-0 mt-1 mb-3" data-toc-skip>MicroStation VBA-创建圆弧或修改属性</h3><div class="text-muted small"><p> The following small code example describes how to create an arc, find all arcs in the active model and modify some properties like center point color linestyle l...</p></div></div></a></div></div></div><div class="post-navigation d-flex justify-content-between"> <a href="/posts/mstn-vba-line-to-complexlinestring/" class="btn btn-outline-primary" prompt="上一篇"><p>MicroStation VBA创建线段生成线串示例代码</p></a> <a href="/posts/mstn-vba-inner-common-dialog/" class="btn btn-outline-primary" prompt="下一篇"><p>MicroStation VBA调用内置文件对话框</p></a></div></div></div><footer class="row pl-3 pr-3"><div class="col-12 d-flex justify-content-between align-items-center text-muted pl-0 pr-0"><div class="footer-left"><p class="mb-0"> © 2022 <a href="https://twitter.com/qd_xyz">QinDong</a>. <span data-toggle="tooltip" data-placement="top" title="除非另有说明，本网站上的博客文章均由作者按照知识共享署名 4.0 国际 (CC BY 4.0) 许可协议进行授权。">保留部分权利。</span></p></div><div class="footer-right"><p class="mb-0"> 本站由 <a href="https://jekyllrb.com" target="_blank" rel="noopener">Jekyll</a> 生成，采用 <a href="https://github.com/cotes2020/jekyll-theme-chirpy" target="_blank" rel="noopener">Chirpy</a> 主题。</p></div></div></footer></div><div id="search-result-wrapper" class="d-flex justify-content-center unloaded"><div class="col-12 col-sm-11 post-content"><div id="search-hints"><div id="access-tags"><div class="panel-heading">热门标签</div><div class="d-flex flex-wrap mt-3 mb-1 mr-3"> <a class="post-tag" href="/tags/microstation/">MicroStation</a> <a class="post-tag" href="/tags/vba/">VBA</a> <a class="post-tag" href="/tags/%E4%BB%A3%E7%A0%81/">代码</a> <a class="post-tag" href="/tags/xm/">XM</a> <a class="post-tag" href="/tags/openroads/">OpenRoads</a> <a class="post-tag" href="/tags/key-in/">key-in</a> <a class="post-tag" href="/tags/%E6%96%B9%E9%87%8F/">方量</a> <a class="post-tag" href="/tags/civil3d/">Civil3D</a> <a class="post-tag" href="/tags/%E6%95%99%E7%A8%8B/">教程</a> <a class="post-tag" href="/tags/%E6%96%AD%E9%9D%A2/">断面</a></div></div></div><div id="search-results" class="d-flex flex-wrap justify-content-center text-muted mt-3"></div></div></div></div><div id="mask"></div><a id="back-to-top" href="#" aria-label="back-to-top" class="btn btn-lg btn-box-shadow" role="button"> <i class="fas fa-angle-up"></i> </a><div id="notification" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-animation="true" data-autohide="false"><div class="toast-header"> <button type="button" class="ml-2 ml-auto close" data-dismiss="toast" aria-label="Close"> <span aria-hidden="true">&times;</span> </button></div><div class="toast-body text-center pt-0"><p class="pl-2 pr-2 mb-3">发现新版本的内容。</p><button type="button" class="btn btn-primary" aria-label="Update"> 更新 </button></div></div><script src="https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.10.0/dest/simple-jekyll-search.min.js"></script> <script> SimpleJekyllSearch({ searchInput: document.getElementById('search-input'), resultsContainer: document.getElementById('search-results'), json: '/assets/js/data/search.json', searchResultTemplate: '<div class="pl-1 pr-1 pl-sm-2 pr-sm-2 pl-lg-4 pr-lg-4 pl-xl-0 pr-xl-0"> <a href="{url}">{title}</a><div class="post-meta d-flex flex-column flex-sm-row text-muted mt-1 mb-1"> {categories} {tags}</div><p>{snippet}</p></div>', noResultsText: '<p class="mt-5">搜索结果为空</p>', templateMiddleware: function(prop, value, template) { if (prop === 'categories') { if (value === '') { return `${value}`; } else { return `<div class="mr-sm-4"><i class="far fa-folder fa-fw"></i>${value}</div>`; } } if (prop === 'tags') { if (value === '') { return `${value}`; } else { return `<div><i class="fa fa-tag fa-fw"></i>${value}</div>`; } } } }); </script> <script src="https://cdn.jsdelivr.net/combine/npm/magnific-popup@1/dist/jquery.magnific-popup.min.js,npm/lozad/dist/lozad.min.js,npm/clipboard@2/dist/clipboard.min.js"></script> <script src="https://cdn.jsdelivr.net/combine/npm/dayjs@1/dayjs.min.js,npm/dayjs@1/locale/zh.min.js,npm/dayjs@1/plugin/relativeTime.min.js,npm/dayjs@1/plugin/localizedFormat.min.js"></script> <script defer src="/assets/js/dist/post.min.js"></script> <script src="https://cdn.jsdelivr.net/npm/bootstrap@4/dist/js/bootstrap.bundle.min.js"></script> <script defer src="/app.js"></script>
